name: CICD

on: [push, pull_request, workflow_dispatch]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLOUDFRONT_ID: ${{ secrets.CLOUDFRONT_ID_STAGING }}
  AWS_DEFAULT_REGION: us-east-2
  S3_BUCKET: ilfairtax-staging

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-

      - run: npm ci --prefer-offline --no-audit

      - run: npm run lint

      - run: npm run style

      - run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: [checks]
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
    env:
      ELEVENTY_ENV: development
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-

      - run: npm ci --prefer-offline --no-audit

      - uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install AWS CLI
        run: |
          python -m pip install --upgrade pip
          pip install awscli

      - run: npm run build

      - run: ./.deploy.sh
